default:
  tags:
    - ansible
    - x86_64

stages:
  - sanity
  - units
  - webdocs

variables:
  GIT_CLONE_PATH: "$CI_BUILDS_DIR/ansible_collections/yadro/obmc"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHON_INTERPRETER: "/usr/local/bin/python3.8"

cache:
  paths:
    - .cache/pip
    - build/venv

sanity:
  stage: sanity
  script:
    - ./build-tool.sh sanity

units:
  stage: units
  script:
    - ./build-tool.sh units

webdocs:
  stage: webdocs
  script:
    - ./build-tool.sh webdocs
    - mv ./build/html webdocs
  artifacts:
    paths:
      - webdocs
