namespace: yadro
name: obmc
version: 1.1.0
readme: README.md
authors:
  - Radmir Safin <r.safin@yadro.com>
  - Sergey Kovalev <s.kovalev@yadro.com>
description: Yadro OpenBmc Ansible Collection
license:
  - GPL-3.0-or-later
license_file: COPYING
tags: []
dependencies: {}
repository: https://github.com/YADRO-KNS/yadro-ansible-modules
documentation: ***REMOVED***
homepage: https://github.com/YADRO-KNS/yadro-ansible-modules
issues: https://github.com/YADRO-KNS/yadro-ansible-modules/issues
