namespace: yadro
name: obmc
version: 1.0.0
readme: README.md
authors:
  - Radmir Safin <r.safin@yadro.com>
description: Yadro OpenBmc Ansible Collection
license:
  - GPL-2.0-or-later
license_file: ''
tags: []
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore:
  - '.*'
  - build
  - build-tool.sh
